---
title: "Mahomes Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(stringr)
library(nflscrapR)
```

```{r}
pbp = nflscrapR::season_play_by_play(2018)
teams = nflscrapR::nflteams
teams_qbs = nflscrapR::season_rosters(2018, c("KC","NE","NO","GB"), positions = c("QUARTERBACK"))
```

```{r}
mahomes = pbp %>% filter(posteam == "KC", Passer == "P.Mahomes" | Rusher == "P.Mahomes" | PlayType == "Sack", Accepted.Penalty == 0)
brady = pbp %>% filter(posteam == "NE", Passer == "T.Brady" | Rusher == "T.Brady" | PlayType == "Sack", Accepted.Penalty == 0)
brees = pbp %>% filter(posteam == "NO", Passer == "D.Brees" | Rusher == "D.Brees" | PlayType == "Sack", Accepted.Penalty == 0)
rodgers = pbp %>% filter(posteam == "GB", Passer == "A.Rodgers" | Rusher == "A.Rodgers" | PlayType == "Sack", Accepted.Penalty == 0)

qbs = bind_rows(mahomes, brady, brees, rodgers)
```

```{r}
qbs %>% colnames()
```


# Current Year
## Total Yards per QB
```{r}
yards.lost.sack = qbs %>% group_by(posteam) %>% filter(PlayType == "Sack") %>% summarise(yards = sum(Yards.Gained))
qbs_gained_yards = qbs %>% filter(PassOutcome == "Complete", InterceptionThrown == 0, Fumble == 0, PassAttempt == 1, Reception == 1)


total_yards = qbs_gained_yards %>% group_by(posteam) %>% summarise(totalYards = sum(Yards.Gained))#, airYards = sum(AirYards), yardsAfterCatch = sum(YardsAfterCatch))# %>% arrange(desc(totalYards))
total_yards

run_yards = qbs %>% filter(is.na(Passer), InterceptionThrown == 0, Fumble == 0)
run_yards %>% group_by(Rusher) %>% summarise(total = sum(Yards.Gained))
```

## TD/INT
```{r}
td_int_count = function(pbp){
  n_td = qbs %>% filter(PassAttempt == 1, InterceptionThrown == 0, Touchdown == 1) %>% group_by(posteam) %>% summarise(n_TD = n())
  
  n_int = qbs %>% filter(PassAttempt == 1, InterceptionThrown == 1) %>% group_by(posteam) %>% summarise(n_INT = n())
  
  return(data.frame(playResult = c("TD", "Int"), number = c(n_td, n_int)))
}

a = qbs %>% group_by(posteam) %>% do(., td_int_count(.))

```

# First Year of carrer as starting QB
## Total TD/INT
```{r}

```

## Total Yards per QB
```{r}

```

## Yards per attempt
```{r}

```

# 
```{r}

```

