---
title: "Data Preparing"
author: "Allan Sales"
date: "21 de novembro de 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Games formattign
```{r}
game_results = read_csv("nfl_game_results.csv")
game_results = game_results %>% select(Date, `Home Team`, `Away Team`, `Home Score`, `Away Score`)
```

## Add season
```{r}
get_season = function(date){
  month = format(date, "%m") %>% as.integer()
  year = format(date, "%Y") %>% as.integer()
  if(month < 3){
    return(year - 1)
  }
  return(year)
}

game_results = game_results %>% rowwise %>% mutate(Season = get_season(Date))
```

## Add week
```{r}
get_week = function(dates){
  DAY_BEFORE = 1
  dif_of_weeks = difftime(dates, min(dates)-DAY_BEFORE, units = "weeks") %>% as.integer()
  week = dif_of_weeks + 1
  week
}

game_results = game_results %>% group_by(Season) %>% mutate(Week = get_week(Date))
```

## Add day of week
```{r}
game_results$Day_of_week = weekdays(game_results$Date)
```

## Add game type
```{r}
game_results$Type = with(game_results, if_else(Week <= 17, "Regular Season",
                         if_else(Week == 18, "Wild Card",
                                 if_else(Week == 19, "Divisional",
                                         if_else(Week == 20, "Conference",
                                                 "Super Bowl")))))
```

# Power Rankings formating
```{r}
power_rankings = read_csv("python_crawlers/crawlers/spiders/nfl.csv")
preseason_rankings =  power_rankings %>% filter(week == 0)

power_rankings = power_rankings %>% filter(week %in% 0:17)
power_rankings$week = power_rankings$week %>% as.integer()
```

## Add ranking a week before
```{r}
get_previous_rank <- function(data, week_number, team_name, season_year, data_consult){
  if(week_number == 0){
    previous_rank = 0
  } else {
    previous_rank = data_consult %>% filter(week == (week_number-1), team == team_name, year == season_year) %>% select(rank) %>% as.integer()
  }
  return(previous_rank)
}

previous = power_rankings %>% group_by(team, year) %>% rowwise() %>% do(Previous_Rank = get_previous_rank(., .$week, .$team, .$year, power_rankings))
power_rankings = power_rankings %>% bind_cols(Previous_Rank = previous$Previous_Rank %>% unlist()) %>% mutate(Rank_change = rank - Previous_Rank)
```

# Teams results 
```{r}
teams_results = game_results %>% select(Date, Team_target =`Home Team`, Team_adversary = `Away Team`, Team_target_score =`Home Score`, Team_adversary_score =`Away Score`, Season, Week, Day_of_week, Type)
teams_results_2 = game_results %>% select(Date, Team_target = `Away Team`, Team_adversary =`Home Team`, Team_target_score =`Away Score`, Team_adversary_score =`Home Score`, Season, Week, Day_of_week, Type)
teams_results = rbind(teams_results, teams_results_2)
```

## Game features
```{r}
games_context = teams_results %>% inner_join(power_rankings, by = c("Team_target" = "team", "Season" = "year", "Week" = "week"))
games_context = games_context %>% inner_join(power_rankings %>% rename_at(vars(-team, -year, -week),function(x) paste0(x,"_adversary")), by = c("Team_adversary" = "team", "Season" = "year", "Week" = "week"))
```

## Game winner
```{r}
games_context = games_context %>% mutate(Game_winner = if_else(Team_target_score > Team_adversary_score, Team_target, 
                          if_else(Team_target_score < Team_adversary_score, Team_adversary, "Draw")))
```

## Rank difference between teams before game
```{r}
games_context = games_context %>% mutate(Rank_difference_before_game = abs(Previous_Rank - Previous_Rank_adversary))
```

# write data
```{r}
write_csv(games_context, "games_context.csv")

write_csv(power_rankings, "power_rankings.csv")
```

