---
title: "power_rankings"
author: "Allan Sales"
date: "21 de novembro de 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(votesys)
```

# Games formattign
```{r}
game_results = read_csv("nfl_game_results.csv")
game_results = game_results %>% select(Date, `Home Team`, `Away Team`, `Home Score`, `Away Score`)
```

## Add season
```{r}
get_season = function(date){
  month = format(date, "%m") %>% as.integer()
  year = format(date, "%Y") %>% as.integer()
  if(month < 3){
    return(year - 1)
  }
  return(year)
}

game_results = game_results %>% rowwise %>% mutate(Season = get_season(Date))
```

## Add week
```{r}
get_week = function(dates){
  DAY_BEFORE = 1
  dif_of_weeks = difftime(dates, min(dates)-DAY_BEFORE, units = "weeks") %>% as.integer()
  week = dif_of_weeks + 1
  week
}

game_results = game_results %>% group_by(Season) %>% mutate(Week = get_week(Date))
```

## Add day of week
```{r}
game_results$Day_of_week = weekdays(game_results$Date)
```

## Add game type
```{r}
game_results$Type = with(game_results, if_else(Week <= 17, "Regular Season",
                         if_else(Week == 18, "Wild Card",
                                 if_else(Week == 19, "Divisional",
                                         if_else(Week == 20, "Conference",
                                                 "Super Bowl")))))
```

# Power Rankings formating
```{r}
power_rankings = read_csv("python_crawlers/crawlers/spiders/nfl.csv") %>% filter(week %in% 1:17)
power_rankings$week = power_rankings$week %>% as.integer()
```


# Merge power ranking and game results
```{r}
teams_results = game_results %>% select(Date, Team_1 =`Home Team`, Team_2 = `Away Team`, Team_1_score =`Home Score`, Team_2_score =`Away Score`, Season, Week, Day_of_week, Type)
teams_results_2 = game_results %>% select(Date, Team_1 = `Away Team`, Team_2 =`Home Team`, Team_1_score =`Away Score`, Team_2_score =`Home Score`, Season, Week, Day_of_week, Type)
teams_results = rbind(teams_results, teams_results_2)
```

# Game results in voting format
```{r}
produce_voting_format = function(result){
  raw = c(rep(c(result$`Home Team`,result$`Away Team`, result$Season, result$Week), result$`Home Score`),
          rep(c(result$`Away Team`, result$`Home Team`, result$Season, result$Week), result$`Away Score`))
  
  raw = matrix(raw, ncol = 4, byrow = TRUE) %>% as_data_frame()
}

voting_format = game_results %>% rowwise() %>% do(produce_voting_format(.)) #%>% as.matrix()
colnames(voting_format) = c("Home Team", "Away Team", "Season", "Week")
```

# Voting
```{r}
teams = game_results$`Home Team` %>% unique()

s17 = voting_format %>% filter(Season == "2017")

vote <- create_vote(s17 %>% as.matrix(), xtype = 2, candidate = teams)
y <- irv_method(vote)
```

